In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('demo.csv')

In [3]:
df

,id,app,app_version,platform,os_version,model_type,device_id,channel,user_ip,session_id,...,end_time,pagination,target_page_id,code_channel,account_name,search_key,search_type,event_type,context_id,content
0,696809464,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
1,696811067,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.59",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
2,696811068,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.59",1D006168-C7B3-4371-861F-5C334599F7B5,...,2018-12-24 16:01:33,NaN,NaN,NaN,NaN,NaN,NaN,17,NaN,NaN
3,696814168,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
4,696814170,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
5,696814172,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1-234015,NaN
6,696814173,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1-234015,NaN
7,696814174,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1-234015,NaN
8,696814175,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1-234015,NaN
9,696814176,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1-234015,NaN
10,696814177,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1-234015,NaN
11,696814178,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
12,696814180,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
13,696814183,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
14,696814214,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,2018-12-24 16:02:27,1.0,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
15,696814265,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
16,696814300,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
17,696814329,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
18,696815694,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,2018-12-24 16:02:36,2.0,NaN,NaN,NaN,NaN,NaN,2,1-234015,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23..."
19,696815699,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,2018-12-24 16:02:34,5.0,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
20,696815700,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
21,696815703,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,2018-12-24 16:02:36,4.0,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
22,696815707,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
23,696815709,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,2018-12-24 16:02:44,7.0,NaN,NaN,NaN,NaN,NaN,2,NaN,"{\n ""roomId"" : ""6688502"",\n ""projectType"" : ..."
24,696815715,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,2018-12-24 16:02:36,3.0,NaN,NaN,NaN,NaN,NaN,2,NaN,"{""shaiXuan"":""筛选_类型_住宅_开盘时间_下月开盘""}"
25,696815745,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,3室2厅2卫 105㎡ 234015 1
26,696815780,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,2018-12-24 16:02:42,6.0,NaN,NaN,NaN,NaN,NaN,2,NaN,"{\n ""modelId"" : ""2580867"",\n ""projectType"" :..."

In [4]:
from pandas.io.json import json_normalize

In [5]:
df['content']

0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
5                                                   NaN
6                                                   NaN
7                                                   NaN
8                                                   NaN
9                                                   NaN
10                                                  NaN
11                                                  NaN
12                                                  NaN
13                                                  NaN
14                                                  NaN
15                                                  NaN
16                                                  NaN
17                                                  NaN
18    {\n  "projectType" : "1",\n  "projectId" : "23...
19                                                  NaN
20                                                  NaN
21                                                  NaN
22                                                  NaN
23    {\n  "roomId" : "6688502",\n  "projectType" : ...
24                    {"shaiXuan":"筛选_类型_住宅_开盘时间_下月开盘"}
25                                 3室2厅2卫 105㎡ 234015 1
26    {\n  "modelId" : "2580867",\n  "projectType" :...
Name: content, dtype: object

In [6]:
# import json
# def custom(x):
#     try:
#         object=json.loads(x)
#         return (object['roomId'],object['projectType'],object['projectId'])
#     except:
#         return (np.NAN,np.NAN,np.NAN)
    
# (df['roomId'],df['projectType'],df['projectId'])=df['content'].apply(custom)

In [7]:
import json
def custom(df):
    try:
        object=json.loads(df['content'])
        df['roomId']=object.get('roomId',np.NaN)
        df['projectType']=object.get('projectType',np.NaN)
        df['modelId']=object.get('modelId',np.NaN)
        df['projectId']=object.get('projectId',np.NaN)
        df['shaiXuan']=object.get('shaiXuan',np.NaN)
        return df
    except:
        df['roomId']=np.NaN
        df['projectType']=np.NaN
        df['modelId']=np.NaN
        df['projectId']=np.NaN
        df['shaiXuan']=np.NaN
        return df
df=df.apply(custom,axis=1)

In [8]:
df.dropna(subset=['content'])

,id,app,app_version,platform,os_version,model_type,device_id,channel,user_ip,session_id,...,search_key,search_type,event_type,context_id,content,roomId,projectType,modelId,projectId,shaiXuan
18,696815694,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,2,1-234015,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,1,NaN,234015,NaN
23,696815709,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,2,NaN,"{\n ""roomId"" : ""6688502"",\n ""projectType"" : ...",6688502,1,NaN,234015,NaN
24,696815715,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,2,NaN,"{""shaiXuan"":""筛选_类型_住宅_开盘时间_下月开盘""}",NaN,NaN,NaN,NaN,筛选_类型_住宅_开盘时间_下月开盘
25,696815745,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,4,NaN,3室2厅2卫 105㎡ 234015 1,NaN,NaN,NaN,NaN,NaN
26,696815780,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,2,NaN,"{\n ""modelId"" : ""2580867"",\n ""projectType"" :...",NaN,1,2580867,234015,NaN

In [9]:
columns=[ 'PIC_ID','PIC_PRJID','PIC_PRJNAME','PIC_TYPE','PIC_DESC','PIC_TING','PIC_WEI','PIC_CHU','PIC_AREA','PIC_SELL_POINT','PIC_HX_TOTALPRICE' ]
df2=pd.read_csv('newHouseModel.txt', names=columns,header=None ,dtype={'PIC_ID':object})

/Users/michael/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (3,6,7,8,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
df2[:10]

,PIC_ID,PIC_PRJID,PIC_PRJNAME,PIC_TYPE,PIC_DESC,PIC_TING,PIC_WEI,PIC_CHU,PIC_AREA,PIC_SELL_POINT,PIC_HX_TOTALPRICE
0,1,1,东恒阳光嘉园,3,a1 拷贝.jpg,0,0,0,0,NaN,NaN
1,2,1,东恒阳光嘉园,3,a2 拷贝.jpg,0,0,0,0,NaN,NaN
2,3,1,东恒阳光嘉园,3,a3 拷贝.jpg,0,0,0,0,NaN,NaN
3,4,1,东恒阳光嘉园,3,b1 拷贝.jpg,0,0,0,0,NaN,NaN
4,5,1,东恒阳光嘉园,3,b2 拷贝.jpg,0,0,0,0,NaN,NaN
5,6,1,东恒阳光嘉园,3,b3 拷贝.jpg,0,0,0,0,NaN,NaN
6,7,1,东恒阳光嘉园,3,C09-二层平面_w.jpg,0,0,0,0,NaN,NaN
7,8,1,东恒阳光嘉园,3,c1 拷贝.jpg,0,0,0,0,NaN,NaN
8,9,1,东恒阳光嘉园,3,c2 拷贝.jpg,0,0,0,0,NaN,NaN
9,10,1,东恒阳光嘉园,3,c3 拷贝.jpg,0,0,0,0,NaN,NaN

In [11]:
df_model=df.merge(df2,left_on='modelId',right_on='PIC_ID',how='left')

In [12]:
df_model.dropna(subset=['PIC_PRJID'])

,id,app,app_version,platform,os_version,model_type,device_id,channel,user_ip,session_id,...,PIC_PRJID,PIC_PRJNAME,PIC_TYPE,PIC_DESC,PIC_TING,PIC_WEI,PIC_CHU,PIC_AREA,PIC_SELL_POINT,PIC_HX_TOTALPRICE
26,696815780,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,234015.0,熙悦,10,熙悦C户型图105㎡,2,2,1,105,三开间朝南，采光面宽阔,305.87

In [13]:
room_columes=['room_id','flats','price','totalprice']
df3=pd.read_csv('newHouseRoom.txt',header=None,names=room_columes,dtype={'room_id':object})

/Users/michael/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [14]:
df3[:10]

  room_id  flats price  totalprice
0  129685      1   NaN         NaN
1  129683      1   NaN         NaN
2  129681      1   NaN         NaN
3  129679      1   NaN         NaN
4  129677      1   NaN         NaN
5  129675      1   NaN         NaN
6  129673      1   NaN         NaN
7  129671      1   NaN         NaN
8  129669      1   NaN         NaN
9  129667      1   NaN         NaN

In [15]:
df_final=df_model.merge(df3,left_on='roomId',right_on='room_id',how='left')

In [16]:
df_final.dropna(subset=['content'])

,id,app,app_version,platform,os_version,model_type,device_id,channel,user_ip,session_id,...,PIC_TING,PIC_WEI,PIC_CHU,PIC_AREA,PIC_SELL_POINT,PIC_HX_TOTALPRICE,room_id,flats,price,totalprice
18,696815694,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,696815709,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,6688502,4.0,26747,283.33
24,696815715,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,696815745,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,696815780,365淘房,8.0.10,22,12.1,Simulator,443048C5-1ECA-4285-9257-33C45C131FC0,App Store,"218.94.115.131, 172.17.1.60",1D006168-C7B3-4371-861F-5C334599F7B5,...,2,2,1,105,三开间朝南，采光面宽阔,305.87,NaN,NaN,NaN,NaN

In [17]:
df_final['shaiXuan']

0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
5                    NaN
6                    NaN
7                    NaN
8                    NaN
9                    NaN
10                   NaN
11                   NaN
12                   NaN
13                   NaN
14                   NaN
15                   NaN
16                   NaN
17                   NaN
18                   NaN
19                   NaN
20                   NaN
21                   NaN
22                   NaN
23                   NaN
24    筛选_类型_住宅_开盘时间_下月开盘
25                   NaN
26                   NaN
Name: shaiXuan, dtype: object

In [19]:
colName = ["DEVICE_ID", "CONTEXT_ID", "CITY", "DATA_DATE", "LOGIN_ACCOUNT", "START_TIME", "END_TIME", "CONTENT",
                   "OBJECT_ID", "CONTEXT", "OBJECT_ID"]
df = pd.read_csv('newHouseLog.txt', names=colName, header=None,
                         dtype={'LOGIN_ACCOUNT': np.str, 'DATA_DATE': np.str}, delimiter=',')
df

/Users/michael/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/pandas/io/parsers.py:678: UserWarning: Duplicate names specified. This will raise an error in the future.
  return _read(filepath_or_buffer, kwds)
/Users/michael/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,DEVICE_ID,CONTEXT_ID,CITY,DATA_DATE,LOGIN_ACCOUNT,START_TIME,END_TIME,CONTENT,OBJECT_ID,CONTEXT,OBJECT_ID.1
0,263FC589-1874-43CD-8AB4-1997B068E79F,NaN,南京,20190107,13815441746,NaN,NaN,{,NaN,NaN,NaN
1,"""shaiXuan"" : ""位置_区域_浦口区""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,},xflb-sxan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,860477043364719,1-54747,南京,20190107,NaN,2019-01-07 12:00:00.000,2019-01-07 12:00:02.002,NaN,NaN,NaN,NaN
4,865736032556980,1-226517,南京,20190107,NaN,2019-01-07 12:00:01.001,2019-01-07 12:00:27.027,NaN,NaN,NaN,NaN
5,868146038592772,1-249547,南京,20190107,NaN,2019-01-07 12:00:02.002,2019-01-07 12:00:07.007,NaN,NaN,NaN,NaN
6,354732085996916,1-51647,南京,20190107,NaN,2019-01-07 12:00:03.003,2019-01-07 12:00:07.007,NaN,NaN,NaN,NaN
7,864230038200729,1-246861,南京,20190107,NaN,NaN,NaN,NaN,NewHouse-Detail-01,NaN,NaN
8,7EAE093E-DDCE-49BA-A133-DD9641FA7C61,1-229433,南京,20190107,NaN,NaN,NaN,NaN,NewHouse-Detail-01,NaN,NaN
9,0F71AAC6-E1FE-4D3A-B9DE-B9A1D0F2634F,1-187573,南京,20190107,18951741799,NaN,NaN,4室2厅2卫 130㎡ 187573 1,xfxqy-hxlbx,NaN,NaN
10,869874031535451,1-234515,南京,20190107,NaN,2019-01-07 12:00:05.005,2019-01-07 12:00:06.006,NaN,NaN,NaN,NaN
11,7EAE093E-DDCE-49BA-A133-DD9641FA7C61,1-229433,南京,20190107,NaN,NaN,NaN,NaN,NewHouse-Detail-photo-02,NaN,NaN
12,40B538AD-D125-41AB-8A0B-809A0308C3A9,1-1429,南京,20190107,18013892873,2019-01-07 12:00:05.005,2019-01-07 12:00:17.017,NaN,NaN,NaN,NaN
13,06D5CD45-4852-4C5C-9CD1-B0EF56778086,1-148,芜湖,20190107,NaN,2019-01-07 12:00:05.005,2019-01-07 12:00:22.022,NaN,NaN,NaN,NaN
14,A6A6D1B6-48E8-4F0F-9C26-FE3ED5FDA192,5-1540,南京,20190107,NaN,2019-01-07 12:00:05.005,2019-01-07 12:01:14.014,NaN,NaN,NaN,NaN
15,869810032010995,1-260,无锡,20190107,NaN,2019-01-07 12:00:06.006,2019-01-07 12:00:09.009,NaN,NaN,NaN,NaN
16,865297039452533,1-246289,合肥,20190107,18119655554,2019-01-07 12:00:06.006,2019-01-07 12:00:19.019,NaN,NaN,NaN,NaN
17,7244FCC4-B8AC-4042-B8F5-C1EC057AAA59,4-54825,南京,20190107,18942253777,2019-01-07 12:00:06.006,2019-01-07 12:01:43.043,NaN,NaN,NaN,NaN
18,354732085996916,1-51647,南京,20190107,NaN,NaN,NaN,NaN,NewHouse-Detail-01,NaN,NaN
19,354732085996916,1-51647,南京,20190107,NaN,2019-01-07 12:00:08.008,2019-01-07 12:00:24.024,NaN,NaN,NaN,NaN
20,869810032010995,1-260,无锡,20190107,NaN,NaN,NaN,NaN,NewHouse-Detail-12,NaN,NaN
21,865305037064034,1-209867,南京,20190107,NaN,2019-01-07 12:00:09.009,2019-01-07 12:00:22.022,NaN,NaN,NaN,NaN
22,A6A6D1B6-48E8-4F0F-9C26-FE3ED5FDA192,5-1540,南京,20190107,NaN,NaN,NaN,2室2厅1卫 52㎡ 1540 5,xfxqy-hxlbx,NaN,NaN
23,003D2A4C-0272-4BFE-BFFB-CCC3EC4B8FF5,1-249569,南京,20190107,NaN,NaN,NaN,NaN,NewHouse-Detail-01,NaN,NaN
24,40B538AD-D125-41AB-8A0B-809A0308C3A9,1-169969,南京,20190107,18013892873,2019-01-07 12:00:11.011,2019-01-08 12:09:31.031,NaN,NaN,NaN,NaN
25,354732085996916,1-51647,南京,20190107,NaN,NaN,NaN,NaN,xfxqy-qbhx,NaN,NaN
26,867475039575499,1-236693,徐州,20190107,NaN,2019-01-07 12:00:12.012,2019-01-07 12:00:17.017,NaN,NaN,NaN,NaN
27,003D2A4C-0272-4BFE-BFFB-CCC3EC4B8FF5,1-249569,南京,20190107,NaN,NaN,NaN,NaN,NewHouse-Detail-photo-02,NaN,NaN
28,16602DB2-D7FC-4204-B4AA-EFD423DDFB91,1-993,南京,20190107,18260088306,2019-01-07 12:00:13.013,2019-01-07 12:00:34.034,NaN,NaN,NaN,NaN
29,60B9F0EA-DA50-4BD6-9E5F-1CFC83341E04,1-1008,南京,20190107,NaN,2019-01-07 12:00:13.013,2019-01-07 12:02:58.058,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
116085,869379031003534,1-51655,南京,20190107,NaN,2019-01-07 11:59:38.038,2019-01-07 11:59:38.038,NaN,NaN,NaN,NaN
116086,471205E9-3BD4-4C09-8E72-ECCE935FC5B7,1-235961,南京,20190107,15996236183,2019-01-07 11:59:39.039,2019-01-07 11:59:45.045,NaN,NaN,NaN,NaN
116087,865737030862081,1-208077,南京,20190107,NaN,NaN,NaN,NaN,hxlby-hxsx,NaN,NaN
116088,619F4E6F-EDA1-4838-A97B-AAF923AEE563,1-246993,南京,20190107,15151813149,2019-01-07 11:59:39.039,2019-01-08 12:00:43.043,NaN,NaN,NaN,NaN
116089,868773035241234,1-52437,南京,20190107,17625990545,NaN,NaN,NaN,NewHouse-Detail-08,NaN,NaN
116090,868773035241234,1-52437,南京,20190107,17625990545,2019-01-07 11:59:40.040,2019-01-07 11:59:54.054,NaN,NaN,NaN,NaN
116091,867551037063546,1-53831,芜湖,20190107,NaN,NaN,NaN,NaN,NewHouse-Detail-12,NaN,NaN
116092,863293038848252,1-53757,南京,20190107,NaN,2019-01-07 11:59:41.041,2019-01-07 11:59:42.042,NaN,NaN,NaN,NaN
116093,866046033368818,4-249969,芜湖,20190107,NaN,2019-01-07 11:59:43.043,2019-01-07 11:59:45.045,NaN,NaN,NaN,NaN
116094,866150031549427,NaN,安庆,20190107,NaN,NaN,NaN,"{""shaiXuan"":""价格_5000-6000元/㎡""}",xflb-sxan,NaN,NaN
116095,E96EAEC8-2F84-4476-9F9D-6E5BF69EDAC4,1-234877,南京,20190107,15751761668,NaN,NaN,2室2厅1卫 87㎡ 234877 1,hxlby-hxlbx,NaN,NaN
116096,869379031003534,1-232001,南京,20190107,NaN,2019-01-07 11:59:47.047,2019-01-07 11:59:50.050,NaN,NaN,NaN,NaN
116097,93C20074-D2CA-4C4B-88C5-CF425D4A64ED,1-208077,南京,20190107,15365050502,2019-01-07 11:59:48.048,2019-01-07 11:59:49.049,NaN,NaN,NaN,NaN
116098,1AF79588-D4EA-4250-8825-31D1BE0F3C3B,1-577,南京,20190107,15895938552,NaN,NaN,2室2厅2卫 97㎡ 577 1,xfxqy-hxlbx,NaN,NaN
116099,06824CC2-3802-4351-898B-15DCA546B527,1-210162,合肥,20190107,NaN,2019-01-07 11:59:48.048,2019-01-08 12:00:01.001,NaN,NaN,NaN,NaN
116100,863293038848252,4-234199,南京,20190107,NaN,2019-01-07 11:59:49.049,2019-01-08 12:00:05.005,NaN,NaN,NaN,NaN
116101,866147045741917,1-167187,南京,20190107,NaN,2019-01-07 11:59:49.049,2019-01-08 12:00:05.005,NaN,NaN,NaN,NaN
116102,866046033368818,NaN,芜湖,20190107,NaN,NaN,NaN,"{""shaiXuan"":""位置_区域_鸠江区""}",xflb-sxan,NaN,NaN
116103,71851D13-A0CC-4F0B-BE4C-E9A23226F704,1-236255,芜湖,20190107,NaN,2019-01-07 11:59:50.050,2019-01-08 12:00:24.024,NaN,NaN,NaN,NaN
116104,869379031003534,1-232001,南京,20190107,NaN,2019-01-07 11:59:51.051,2019-01-07 11:59:51.051,NaN,NaN,NaN,NaN
116105,2D4BB179-E6CD-4FA6-AA24-831CE1558E9D,5-238125,南京,20190107,13813966831,2019-01-07 11:59:51.051,2019-01-08 12:29:13.013,NaN,NaN,NaN,NaN
116106,93C20074-D2CA-4C4B-88C5-CF425D4A64ED,1-208077,南京,20190107,15365050502,2019-01-07 11:59:52.052,2019-01-08 12:00:04.004,NaN,NaN,NaN,NaN
116107,862023039185896,1-240961,杭州,20190107,NaN,2019-01-07 11:59:53.053,2019-01-07 11:59:59.059,NaN,NaN,NaN,NaN
116108,869818027996003,NaN,西安,20190107,18909145523,NaN,NaN,"{""shaiXuan"":""位置_地铁_三号线_广泰门""}",xflb-sxan,NaN,NaN
116109,865970039607906,1-90197,天津,20190107,NaN,2019-01-07 11:59:54.054,2019-01-07 11:59:59.059,NaN,NaN,NaN,NaN
116110,61D1433B-AD0A-45BF-832D-62C39F957059,1-102453,南京,20190107,NaN,2019-01-07 11:59:54.054,2019-01-08 12:00:51.051,NaN,NaN,NaN,NaN
116111,159CD5FE-2110-4D10-95F1-D7F1FF7A3ACE,1-1250,南京,20190107,13605182360,2019-01-07 11:59:55.055,2019-01-07 11:59:57.057,NaN,NaN,NaN,NaN
116112,865982028921420,1-54595,南京,20190107,NaN,2019-01-07 11:59:55.055,2019-01-08 12:00:00.000,NaN,NaN,NaN,NaN
116113,99001008629165,1-238195,芜湖,20190107,NaN,NaN,NaN,NaN,xfxq-fdxx,NaN,NaN
116114,B28E8251-4E03-4D1C-860F-47A67BB496E8,1-54595,南京,20190107,NaN,NaN,NaN,NaN,xfxq-lpdglbx,NaN,NaN