In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('demo.csv')

/Users/michael/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (1,14,24,25,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.head(100)

,Unnamed: 0,DEVICE_ID,CONTEXT_ID,CITY_x,DATA_DATE,LOGIN_ACCOUNT,START_TIME,END_TIME,CONTENT,OBJECT_ID,...,PIC_TING,PIC_WEI,PIC_CHU,PIC_AREA,PIC_SELL_POINT,PIC_HX_TOTALPRICE,ROOM_ID,FLATS,PRICE,TOTALPRICE
0,35624,00000000,4-249969,芜湖,2019-02-10 00:00:00.000,NaN,2019-02-10 02:01:56.056,2019-02-10 02:01:57.057,"{\n ""projectType"" : ""4"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,35625,00000000,4-249969,芜湖,2019-02-10 00:00:00.000,NaN,2019-02-10 02:01:58.058,2019-02-10 02:01:58.058,"{\n ""projectType"" : ""4"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,35626,00000000,4-249969,芜湖,2019-02-10 00:00:00.000,NaN,2019-02-10 02:01:57.057,2019-02-10 02:01:58.058,"{\n ""projectType"" : ""4"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,35627,00000000,1-241647,芜湖,2019-02-10 00:00:00.000,NaN,2019-02-10 02:01:19.019,2019-02-10 02:01:49.049,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,43644,00000000,1-1402,南京,2019-02-10 00:00:00.000,NaN,2019-02-10 03:45:09.009,2019-02-10 03:45:10.010,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""14...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,43646,00000000,1-1402,南京,2019-02-10 00:00:00.000,NaN,2019-02-10 03:45:07.007,2019-02-10 03:45:09.009,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""14...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,43675,00000000,1-1402,南京,2019-02-10 00:00:00.000,NaN,2019-02-10 03:45:10.010,2019-02-10 03:45:22.022,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""14...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,43713,00000000,1-51655,南京,2019-02-10 00:00:00.000,NaN,2019-02-10 03:45:42.042,2019-02-10 03:45:43.043,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""51...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,43714,00000000,1-51655,南京,2019-02-10 00:00:00.000,NaN,2019-02-10 03:45:43.043,2019-02-10 03:45:48.048,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""51...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,43961,00000000,1-51655,南京,2019-02-10 00:00:00.000,NaN,2019-02-10 03:48:39.039,2019-02-10 03:48:44.044,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""51...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,43962,00000000,1-51655,南京,2019-02-10 00:00:00.000,NaN,2019-02-10 03:48:44.044,2019-02-10 03:48:51.051,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""51...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,212908,00000000,1-54595,南京,2019-02-11 00:00:00.000,1.876188e+10,2019-02-11 11:54:14.014,2019-02-11 11:54:30.030,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""54...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,213028,00000000,1-54595,南京,2019-02-11 00:00:00.000,1.876188e+10,2019-02-11 11:55:31.031,2019-02-11 11:55:36.036,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""54...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,213114,00000000,1-54595,南京,2019-02-11 00:00:00.000,1.876188e+10,2019-02-11 11:55:57.057,2019-02-11 11:56:03.003,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""54...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,213559,00000000,1-54595,南京,2019-02-11 00:00:00.000,1.876188e+10,2019-02-11 11:56:54.054,2019-02-11 11:56:56.056,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""54...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,250618,00000000,1-236275,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:23:13.013,2019-02-12 12:23:15.015,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,250822,00000000,1-249569,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:25:14.014,2019-02-12 12:25:15.015,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,250824,00000000,1-249569,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:23:54.054,2019-02-12 12:25:08.008,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,250825,00000000,1-249569,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:25:08.008,2019-02-12 12:25:14.014,"{\n ""modelId"" : ""2728379"",\n ""projectType"" :...",NaN,...,2,2,1.0,128.0,采光充足 三卧朝南,557,NaN,NaN,NaN,NaN
19,250857,00000000,1-249569,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:25:15.015,2019-02-12 12:25:29.029,"{\n ""modelId"" : ""2728379"",\n ""projectType"" :...",NaN,...,2,2,1.0,128.0,采光充足 三卧朝南,557,NaN,NaN,NaN,NaN
20,250858,00000000,1-249569,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:25:39.039,2019-02-12 12:25:41.041,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,250859,00000000,1-249569,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:25:29.029,2019-02-12 12:25:31.031,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,250860,00000000,1-249569,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:25:31.031,2019-02-12 12:25:39.039,"{\n ""modelId"" : ""2728379"",\n ""projectType"" :...",NaN,...,2,2,1.0,128.0,采光充足 三卧朝南,557,NaN,NaN,NaN,NaN
23,250901,00000000,1-249569,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:25:45.045,2019-02-12 12:25:49.049,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,251403,00000000,1-249569,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:28:04.004,2019-02-12 12:28:08.008,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,251453,00000000,1-249569,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:29:57.057,2019-02-12 12:29:58.058,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,251533,00000000,1-236275,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:30:47.047,2019-02-12 12:30:48.048,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,251534,00000000,1-236275,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:30:48.048,2019-02-12 12:30:50.050,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,251535,00000000,1-236275,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:30:50.050,2019-02-12 12:30:54.054,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,251596,00000000,1-236275,南京,2019-02-12 00:00:00.000,NaN,2019-02-12 12:30:54.054,2019-02-12 12:31:14.014,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,128327,0000cfe70000fa82,1-54595,南京,2019-02-11 00:00:00.000,NaN,2019-02-11 12:17:24.024,2019-02-11 12:17:53.053,"{""projectType"":""1"",""projectId"":""54595"",""modelI...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,128334,0000cfe70000fa82,1-54595,南京,2019-02-11 00:00:00.000,NaN,2019-02-11 12:17:58.058,2019-02-11 12:18:00.000,"{""projectType"":""1"",""projectId"":""54595"",""modelI...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,128342,0000cfe70000fa82,1-54595,南京,2019-02-11 00:00:00.000,NaN,2019-02-11 12:18:08.008,2019-02-11 12:18:11.011,"{""projectType"":""1"",""projectId"":""54595"",""modelI...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,128644,0000cfe70000fa82,1-54595,南京,2019-02-11 00:00:00.000,NaN,2019-02-11 12:21:42.042,2019-02-11 12:21:43.043,"{""projectType"":""1"",""projectId"":""54595"",""modelI...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,410452,00044104-1811-4ABC-98EE-7530228BDBB6,1-789,合肥,2019-02-13 00:00:00.000,NaN,2019-02-13 03:42:31.031,2019-02-13 03:44:16.016,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""78...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,538958,000B33FF-F235-424F-BD89-501F69CE3571,1-305,南京,2019-02-14 00:00:00.000,NaN,2019-02-14 03:59:25.025,2019-02-14 04:00:28.028,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""30...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,539041,000B33FF-F235-424F-BD89-501F69CE3571,1-102453,南京,2019-02-14 00:00:00.000,NaN,2019-02-14 04:00:10.010,2019-02-14 04:00:59.059,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""10...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,539092,000B33FF-F235-424F-BD89-501F69CE3571,1-102453,南京,2019-02-14 00:00:00.000,NaN,2019-02-14 04:00:18.018,2019-02-14 04:01:28.028,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""10...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,539197,000B33FF-F235-424F-BD89-501F69CE3571,1-236397,南京,2019-02-14 00:00:00.000,NaN,2019-02-14 04:00:38.038,2019-02-14 04:02:09.009,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,539243,000B33FF-F235-424F-BD89-501F69CE3571,1-241535,南京,2019-02-14 00:00:00.000,NaN,2019-02-14 04:01:21.021,2019-02-14 04:02:27.027,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,539244,000B33FF-F235-424F-BD89-501F69CE3571,5-236603,南京,2019-02-14 00:00:00.000,NaN,2019-02-14 04:02:09.009,2019-02-14 04:02:23.023,"{\n ""modelId"" : ""2629977"",\n ""projectType"" :...",NaN,...,2,1,1.0,79.0,公寓户型 挑高,260,NaN,NaN,NaN,NaN
81,539293,000B33FF-F235-424F-BD89-501F69CE3571,5-236603,南京,2019-02-14 00:00:00.000,NaN,2019-02-14 04:02:27.027,2019-02-14 04:02:30.030,"{\n ""modelId"" : ""2629977"",\n ""projectType"" :...",NaN,...,2,1,1.0,79.0,公寓户型 挑高,260,NaN,NaN,NaN,NaN
82,539337,000B33FF-F235-424F-BD89-501F69CE3571,5-236603,南京,2019-02-14 00:00:00.000,NaN,2019-02-14 04:01:57.057,2019-02-14 04:02:51.051,"{\n ""projectType"" : ""5"",\n ""projectId"" : ""23...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,361731,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-54055,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 08:45:48.048,2019-02-13 08:46:50.050,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,361758,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-54055,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 08:46:27.027,2019-02-13 08:46:59.059,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,387400,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-117255,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 08:46:42.042,2019-02-13 08:47:19.019,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,387714,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-117255,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 08:46:58.058,2019-02-13 12:36:58.058,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,387765,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-54335,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 08:47:07.007,2019-02-13 12:37:31.031,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,387819,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-550,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 12:37:28.028,2019-02-13 12:37:46.046,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,387820,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-54051,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 12:36:56.056,2019-02-13 12:37:44.044,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,388229,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-550,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 12:37:32.032,2019-02-13 12:40:48.048,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,388230,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-550,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 12:37:45.045,2019-02-13 12:40:51.051,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,388341,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-550,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 12:40:49.049,2019-02-13 12:41:31.031,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,388342,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-550,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 12:40:20.020,2019-02-13 12:41:25.025,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,388409,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-241599,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 12:40:54.054,2019-02-13 12:41:47.047,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,388450,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-241599,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 12:41:25.025,2019-02-13 12:42:05.005,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,388510,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-241599,无锡,2019-02-13 00:00:00.000,NaN,2019-02-13 12:41:46.046,2019-02-13 12:42:16.016,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,388695,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-102251,南京,2019-02-13 00:00:00.000,NaN,2019-02-13 12:42:02.002,2019-02-13 12:43:49.049,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,388696,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-102251,南京,2019-02-13 00:00:00.000,NaN,2019-02-13 12:42:15.015,2019-02-13 12:43:52.052,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,388738,000B60AB-D0A1-4552-98A1-E1FC90C19643,1-241097,南京,2019-02-13 00:00:00.000,NaN,2019-02-13 12:43:20.020,2019-02-13 12:43:57.057,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594536 entries, 0 to 594535
Data columns (total 43 columns):
Unnamed: 0           594536 non-null int64
DEVICE_ID            594536 non-null object
CONTEXT_ID           594536 non-null object
CITY_x               594536 non-null object
DATA_DATE            594536 non-null object
LOGIN_ACCOUNT        183001 non-null float64
START_TIME           594536 non-null object
END_TIME             594536 non-null object
CONTENT              550896 non-null object
OBJECT_ID            0 non-null float64
CHANNEL              594536 non-null float64
CONTEXT              594536 non-null float64
ROOMID               9822 non-null float64
PROJECTTYPE          550896 non-null float64
MODELID              152505 non-null object
PROJECTID            550896 non-null float64
SHAIXUAN             0 non-null float64
PRJ_LISTID           580202 non-null float64
CITY_y               580202 non-null object
CITY_NAME            580202 non-null object
PRJ_ITEMNAME         580202 non-null object
PRJ_LOC              579942 non-null object
PRJ_DECORATE         555876 non-null object
PRJ_VIEWS            579964 non-null object
B_LNG                580202 non-null object
B_LAT                580202 non-null object
PRICE_AVG            580195 non-null float64
PRICE_SHOW           520477 non-null object
PIC_ID               152501 non-null float64
PIC_PRJID            152501 non-null float64
PIC_PRJNAME          152501 non-null object
PIC_TYPE             152501 non-null float64
PIC_DESC             152501 non-null object
PIC_TING             152501 non-null object
PIC_WEI              152501 non-null object
PIC_CHU              152501 non-null float64
PIC_AREA             152501 non-null float64
PIC_SELL_POINT       139639 non-null object
PIC_HX_TOTALPRICE    101906 non-null object
ROOM_ID              9822 non-null float64
FLATS                9822 non-null float64
PRICE                8641 non-null float64
TOTALPRICE           8635 non-null float64
dtypes: float64(19), int64(1), object(23)
memory usage: 195.0+ MB

In [6]:
df.groupby('DATA_DATE').size()

DATA_DATE
2019-02-10 00:00:00.000     91993
2019-02-11 00:00:00.000    121715
2019-02-12 00:00:00.000    134392
2019-02-13 00:00:00.000    132155
2019-02-14 00:00:00.000    114281
dtype: int64

In [7]:
for date, group in df.groupby('DATA_DATE'):
    print(date)
    print(group[group['PIC_HX_TOTALPRICE'].notna()].shape[0])

2019-02-10 00:00:00.000
15666
2019-02-11 00:00:00.000
20643
2019-02-12 00:00:00.000
22799
2019-02-13 00:00:00.000
23117
2019-02-14 00:00:00.000
19681

In [4]:
df[df['PIC_HX_TOTALPRICE'].notna()].shape[0]

101906

In [12]:
df.groupby('DEVICE_ID').size().reset_index(name='count').sort_values(by='count',ascending=False)

                                  DEVICE_ID  count
5554   0808A810-141D-471E-AD23-4BA2FE91D87B   1020
653                         863447030503899   1009
26637                       867788044589994    875
29826                       869979036453004    812
25227                       866875033490341    612
19953                       864665035259568    596
10496  44643D1C-97B0-4383-8FFD-502E92458A6A    590
6785   1BDF5A3A-53BC-437A-BE35-8CE716CDAE45    542
16354                       861608040195099    540
38112  E6F7E86B-9A1C-4424-9CFA-1B78DA2F9697    540
37947  E4012B9F-63BF-4D81-A4D1-A11A5B6F7BDC    505
16208                       861451035639510    498
8880                        354765080856701    490
14045  77E60B1E-4E42-4255-AD36-DB8CEE1C3948    481
39613  FE3102AC-B6A3-4650-9244-955C938159C7    466
9684   39137A33-F0C0-43C6-B5C6-84FF7C1FBFF4    463
16194                       861438048929632    462
39395  FAC3A5D1-6D07-4519-8E86-3014E2401924    457
10090  3EAEFE54-8392-4E39-82CE-992FAAAA1F43    447
34181  AB113820-03D5-4312-A276-2BEDD976F415    439
20392                       864815044184816    438
10165  3FB571C7-84D7-4B37-898E-4C56A3EF5F7E    437
14072  78489C86-3879-4027-B1DD-0697D8925FA4    433
24552                       866592038734157    422
36101  C8BE03BE-089F-465F-A62A-7F8070714774    420
28131                       869000044090041    405
26210                       867601033336295    395
28649                       869169035321994    387
32944                        A000007418241D    384
30526  8F828A91-04B1-4AE6-ABBA-A937464A0B32    381
...                                     ...    ...
31205                       990007181056729      1
21007                       865216030999631      1
7230   22F50532-BCF8-4D47-B538-728EC97E2CC7      1
31211                        99000763837587      1
21006                       865214039961165      1
31216                        99000812031126      1
31217                        99000812269958      1
31218                        99000812413426      1
21005                       865214039679502      1
31222                        99000812681319      1
7205   22A133C5-6BCB-4890-9B4D-E13FB0A3396B      1
7206   22A1FA2A-366D-4209-A4FD-CF47F5825B4A      1
31179                        99000706539312      1
31178                        99000695892043      1
31151                        99000245520479      1
21016                       865217033381942      1
31154                        99000479749587      1
7228   22E8F379-D807-4EB2-AEA1-FC316B2F93A4      1
7227   22E7D5DF-7ED8-4CF8-8AD5-D165552704CE      1
15239                       860219044494487      1
31165                        99000645616361      1
31166                        99000662672761      1
31167                        99000663165432      1
7213   22B9E3FB-4298-4275-9B5F-3CDC2CFFB622      1
31169                        99000663336821      1
7210   22B1D36B-0331-4CA7-BBA4-DCDB68C9DE16      1
21011                       865216036154637      1
31175                        99000695500508      1
7207   22A66149-C7FA-47C9-AD59-FDDE938C9A7C      1
17551                       862720037229820      1

[39919 rows x 2 columns]

In [ ]:
df[df['MODELID'].notna()]

In [29]:
df[df['DEVICE_ID']=='1BDF5A3A-53BC-437A-BE35-8CE716CDAE45']['LOGIN_ACCOUNT'].notna()

30416    False
30417    False
30418    False
30419    False
30420    False
30421    False
30422    False
30423    False
30424    False
30425    False
30426    False
30427    False
30428    False
30429    False
30430    False
30431    False
30432    False
30433    False
30434    False
30435    False
30436    False
30437    False
30438    False
30439    False
30440    False
30441    False
30442    False
30443    False
30444    False
30445    False
         ...
30928    False
30929    False
30930    False
30931    False
30932    False
30933    False
30934    False
30935    False
30936    False
30937    False
30938    False
30939    False
30940    False
30941    False
30942    False
30943    False
30944    False
30945    False
30946    False
30947    False
30948    False
30949    False
30950    False
30951    False
30952    False
30953    False
30954    False
30955    False
30956    False
30957    False
Name: LOGIN_ACCOUNT, Length: 542, dtype: bool

In [30]:
df[df['DEVICE_ID']=='1BDF5A3A-53BC-437A-BE35-8CE716CDAE45']['LOGIN_ACCOUNT'].notna()

/Users/michael/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match

In [27]:
df.ix[94169]['LOGIN_ACCOUNT']

/Users/michael/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

19951953059.0

In [ ]:
# from pandas.io.json import json_normalize

In [ ]:
# df['content']

In [ ]:
# import json
# def custom(x):
#     try:
#         object=json.loads(x)
#         return (object['roomId'],object['projectType'],object['projectId'])
#     except:
#         return (np.NAN,np.NAN,np.NAN)
    
# (df['roomId'],df['projectType'],df['projectId'])=df['content'].apply(custom)

In [ ]:
# import json
# def custom(df):
#     try:
#         object=json.loads(df['content'])
#         df['roomId']=object.get('roomId',np.NaN)
#         df['projectType']=object.get('projectType',np.NaN)
#         df['modelId']=object.get('modelId',np.NaN)
#         df['projectId']=object.get('projectId',np.ALLOW_THREADSNaN)
#         df['shaiXuan']=object.get('shaiXuan',np.NaN)
#         return df
#     except:
#         df['roomId']=np.NaN
#         df['projectType']=np.NaN
#         df['modelId']=np.NaN
#         df['projectId']=np.NaN
#         df['shaiXuan']=np.NaN
#         return df

# def custom(df):
#     try:
#         object = json.loads(df['CONTENT'])
#         df['ROOMID'] = object.get('roomId', np.NaN)
#         df['PROJECTTYPE'] = object.get('projectType', np.NaN)
#         df['MODELID'] = object.get('modelId', np.NaN)
#         df['PROJECTID'] = object.get('projectId', np.NaN)
#         df['SHAIXUAN'] = object.get('shaiXuan', np.NaN)
#         return df
#     except:
#         df['ROOMID'] = np.NaN
#         df['PROJECTTYPE'] = np.NaN
#         df['MODELID'] = np.NaN
#         df['PROJECTID'] = np.NaN
#         df['SHAIXUAN'] = np.NaN
#         return df
    
# df=df.apply(custom,axis=1)

In [ ]:
df[df['']]

In [ ]:
# df.dropna(subset=['CONTENT'])

In [ ]:
# columns=[ 'PIC_ID','PIC_PRJID','PIC_PRJNAME','PIC_TYPE','PIC_DESC','PIC_TING','PIC_WEI','PIC_CHU','PIC_AREA','PIC_SELL_POINT','PIC_HX_TOTALPRICE' ]
# df2=pd.read_csv('newHouseModel.txt', names=columns,header=None ,dtype={'PIC_ID':object})

In [ ]:
# df2[:10]

In [ ]:
# df.info()

In [ ]:
# df2.info()

In [ ]:
# df_model=df.merge(df2,left_on='MODELID',right_on='PIC_ID',how='left')

In [ ]:
# df_model.dropna(subset=['PIC_PRJID'])

In [ ]:
# room_columes=['room_id','flats','price','totalprice']
# df3=pd.read_csv('newHouseRoom.txt',header=None, names=room_columes, dtype={'room_id':object} ,low_memory=False)

In [ ]:
# df3[:10]

In [ ]:
# df_final=df_model.merge(df3,left_on='ROOMID',right_on='room_id',how='left')

In [ ]:
# df_final.dropna(subset=['CONTENT'])