In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('newhouseLog.csv')

In [3]:
df

,B_LAT,B_LNG,CHANNEL,CITY_NAME,CITY_x,CITY_y,CONTENT,CONTEXT,CONTEXT_ID,DATA_DATE,...,PRJ_LISTID,PRJ_LOC,PRJ_VIEWS,PROJECTID,PROJECTTYPE,ROOMID,ROOM_ID,SHAIXUAN,START_TIME,TOTALPRICE
0,32.037937,118.917856,1,南京,南京,nj,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",234015,1-234015,1548028800000,...,234015,麒麟街道运粮河东路99号,66392,234015,1,NaN,NaN,NaN,2019-01-21 10:34:04.004,NaN
1,32.037937,118.917856,1,南京,南京,nj,"{\n ""modelId"" : ""2580865"",\n ""projectType"" :...",234015,1-234015,1548028800000,...,234015,麒麟街道运粮河东路99号,66392,234015,1,NaN,NaN,NaN,2019-01-21 10:34:09.009,NaN
2,32.037937,118.917856,1,南京,南京,nj,"{\n ""roomId"" : ""6688300"",\n ""projectType"" : ...",234015,1-234015,1548028800000,...,234015,麒麟街道运粮河东路99号,66392,234015,1,NaN,NaN,NaN,2019-01-21 10:34:13.013,NaN
3,32.037937,118.917856,1,南京,南京,nj,"{\n ""modelId"" : ""2580865"",\n ""projectType"" :...",234015,1-234015,1548028800000,...,234015,麒麟街道运粮河东路99号,66392,234015,1,NaN,NaN,NaN,2019-01-21 10:34:15.015,NaN
4,32.037937,118.917856,1,南京,南京,nj,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",234015,1-234015,1548028800000,...,234015,麒麟街道运粮河东路99号,66392,234015,1,NaN,NaN,NaN,2019-01-21 10:34:15.015,NaN
5,32.113119,118.759805,1,南京,南京,nj,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""10...",102453,1-102453,1548028800000,...,102453,宝塔桥西街155号(金川河西路与城河北路交汇处),185673,102453,1,NaN,NaN,NaN,2019-01-21 10:34:19.019,NaN
6,32.113119,118.759805,1,南京,南京,nj,"{\n ""modelId"" : ""2763050"",\n ""projectType"" :...",102453,1-102453,1548028800000,...,102453,宝塔桥西街155号(金川河西路与城河北路交汇处),185673,102453,1,NaN,NaN,NaN,2019-01-21 10:34:25.025,NaN
7,32.113119,118.759805,1,南京,南京,nj,"{\n ""roomId"" : ""6676874"",\n ""projectType"" : ...",102453,1-102453,1548028800000,...,102453,宝塔桥西街155号(金川河西路与城河北路交汇处),185673,102453,1,NaN,NaN,NaN,2019-01-21 10:34:30.030,NaN
8,32.113119,118.759805,1,南京,南京,nj,"{\n ""modelId"" : ""2763050"",\n ""projectType"" :...",102453,1-102453,1548028800000,...,102453,宝塔桥西街155号(金川河西路与城河北路交汇处),185673,102453,1,NaN,NaN,NaN,2019-01-21 10:34:33.033,NaN
9,32.113119,118.759805,1,南京,南京,nj,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""10...",102453,1-102453,1548028800000,...,102453,宝塔桥西街155号(金川河西路与城河北路交汇处),185673,102453,1,NaN,NaN,NaN,2019-01-21 10:34:34.034,NaN
10,32.081739,118.692504,1,南京,南京,nj,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",241535,1-241535,1548028800000,...,241535,江北核心区七里河大街与九袱州路交汇处,44440,241535,1,NaN,NaN,NaN,2019-01-21 10:34:38.038,NaN
11,32.081739,118.692504,1,南京,南京,nj,"{\n ""modelId"" : ""2583585"",\n ""projectType"" :...",241535,1-241535,1548028800000,...,241535,江北核心区七里河大街与九袱州路交汇处,44440,241535,1,NaN,NaN,NaN,2019-01-21 10:34:42.042,NaN
12,32.081739,118.692504,1,南京,南京,nj,"{\n ""roomId"" : ""5519645"",\n ""projectType"" : ...",241535,1-241535,1548028800000,...,241535,江北核心区七里河大街与九袱州路交汇处,44440,241535,1,NaN,NaN,NaN,2019-01-21 10:34:48.048,NaN
13,32.081739,118.692504,1,南京,南京,nj,"{\n ""modelId"" : ""2583585"",\n ""projectType"" :...",241535,1-241535,1548028800000,...,241535,江北核心区七里河大街与九袱州路交汇处,44440,241535,1,NaN,NaN,NaN,2019-01-21 10:34:51.051,NaN
14,32.081739,118.692504,1,南京,南京,nj,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",241535,1-241535,1548028800000,...,241535,江北核心区七里河大街与九袱州路交汇处,44440,241535,1,NaN,NaN,NaN,2019-01-21 10:34:52.052,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 42 columns):
B_LAT                15 non-null float64
B_LNG                15 non-null float64
CHANNEL              15 non-null int64
CITY_NAME            15 non-null object
CITY_x               15 non-null object
CITY_y               15 non-null object
CONTENT              15 non-null object
CONTEXT              15 non-null int64
CONTEXT_ID           15 non-null object
DATA_DATE            15 non-null int64
DEVICE_ID            15 non-null object
END_TIME             15 non-null object
FLATS                0 non-null float64
LOGIN_ACCOUNT        15 non-null int64
MODELID              6 non-null float64
OBJECT_ID            0 non-null float64
PIC_AREA             6 non-null float64
PIC_CHU              6 non-null float64
PIC_DESC             6 non-null object
PIC_HX_TOTALPRICE    6 non-null float64
PIC_ID               6 non-null float64
PIC_PRJID            6 non-null float64
PIC_PRJNAME          6 non-null object
PIC_SELL_POINT       6 non-null object
PIC_TING             6 non-null float64
PIC_TYPE             6 non-null float64
PIC_WEI              6 non-null float64
PRICE                0 non-null float64
PRICE_AVG            15 non-null int64
PRICE_SHOW           15 non-null object
PRJ_DECORATE         15 non-null object
PRJ_ITEMNAME         15 non-null object
PRJ_LISTID           15 non-null int64
PRJ_LOC              15 non-null object
PRJ_VIEWS            15 non-null int64
PROJECTID            15 non-null int64
PROJECTTYPE          15 non-null int64
ROOMID               0 non-null float64
ROOM_ID              0 non-null float64
SHAIXUAN             0 non-null float64
START_TIME           15 non-null object
TOTALPRICE           0 non-null float64
dtypes: float64(18), int64(9), object(15)
memory usage: 5.0+ KB

In [5]:
df[['CONTEXT_ID','DEVICE_ID','LOGIN_ACCOUNT','CONTENT','ROOMID','MODELID']]

,CONTEXT_ID,DEVICE_ID,LOGIN_ACCOUNT,CONTENT,ROOMID,MODELID
0,1-234015,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,NaN
1,1-234015,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2580865"",\n ""projectType"" :...",NaN,2580865.0
2,1-234015,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""roomId"" : ""6688300"",\n ""projectType"" : ...",NaN,NaN
3,1-234015,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2580865"",\n ""projectType"" :...",NaN,2580865.0
4,1-234015,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,NaN
5,1-102453,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""10...",NaN,NaN
6,1-102453,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2763050"",\n ""projectType"" :...",NaN,2763050.0
7,1-102453,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""roomId"" : ""6676874"",\n ""projectType"" : ...",NaN,NaN
8,1-102453,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2763050"",\n ""projectType"" :...",NaN,2763050.0
9,1-102453,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""10...",NaN,NaN
10,1-241535,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,NaN
11,1-241535,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2583585"",\n ""projectType"" :...",NaN,2583585.0
12,1-241535,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""roomId"" : ""5519645"",\n ""projectType"" : ...",NaN,NaN
13,1-241535,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2583585"",\n ""projectType"" :...",NaN,2583585.0
14,1-241535,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,NaN

In [6]:
df[['CONTEXT_ID','DEVICE_ID','LOGIN_ACCOUNT','CONTENT','ROOMID','MODELID','PIC_ID', 'PIC_PRJID', 'PIC_PRJNAME', 'PIC_TYPE', 'PIC_DESC', 'PIC_TING', 'PIC_WEI', 'PIC_CHU',
                   'PIC_AREA', 'PIC_SELL_POINT', 'PIC_HX_TOTALPRICE','FLATS']]

,CONTEXT_ID,DEVICE_ID,LOGIN_ACCOUNT,CONTENT,ROOMID,MODELID,PIC_ID,PIC_PRJID,PIC_PRJNAME,PIC_TYPE,PIC_DESC,PIC_TING,PIC_WEI,PIC_CHU,PIC_AREA,PIC_SELL_POINT,PIC_HX_TOTALPRICE,FLATS
0,1-234015,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1-234015,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2580865"",\n ""projectType"" :...",NaN,2580865.0,2580865.0,234015.0,熙悦,9.0,熙悦A户型图99㎡,2.0,2.0,1.0,99.0,南北通透、采光好,288.61,NaN
2,1-234015,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""roomId"" : ""6688300"",\n ""projectType"" : ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1-234015,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2580865"",\n ""projectType"" :...",NaN,2580865.0,2580865.0,234015.0,熙悦,9.0,熙悦A户型图99㎡,2.0,2.0,1.0,99.0,南北通透、采光好,288.61,NaN
4,1-234015,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""23...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1-102453,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""10...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1-102453,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2763050"",\n ""projectType"" :...",NaN,2763050.0,2763050.0,102453.0,中冶盛世滨江,11.0,中冶盛世滨江B-1户型173㎡,2.0,3.0,1.0,173.0,户型方正、三开间朝南,679.53,NaN
7,1-102453,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""roomId"" : ""6676874"",\n ""projectType"" : ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1-102453,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2763050"",\n ""projectType"" :...",NaN,2763050.0,2763050.0,102453.0,中冶盛世滨江,11.0,中冶盛世滨江B-1户型173㎡,2.0,3.0,1.0,173.0,户型方正、三开间朝南,679.53,NaN
9,1-102453,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""10...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1-241535,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1-241535,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2583585"",\n ""projectType"" :...",NaN,2583585.0,2583585.0,241535.0,扬子江金茂悦,10.0,扬子江金茂悦110㎡三室两厅一卫户型,2.0,1.0,1.0,110.0,双卧朝南 采光好,336.29,NaN
12,1-241535,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""roomId"" : ""5519645"",\n ""projectType"" : ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1-241535,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""modelId"" : ""2583585"",\n ""projectType"" :...",NaN,2583585.0,2583585.0,241535.0,扬子江金茂悦,10.0,扬子江金茂悦110㎡三室两厅一卫户型,2.0,1.0,1.0,110.0,双卧朝南 采光好,336.29,NaN
14,1-241535,A5B9DA9F-40C6-4DE4-9539-3A288CE6B614,18118849310,"{\n ""projectType"" : ""1"",\n ""projectId"" : ""24...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN